Add nwm_client documentation and minor subpackage level import changes
NOAA-OWP/hydrotools pull request #179
Opened 2022-02-10 23:59 UTC by aaraney

Update / add too / fix issues with `nwm_client` readme and docstrings.  Adds usage example for `gcp` client to readme.

## Additions

- `nwm_client` submodule members, `gcp` and `http` can now be accessed from the subpackage level.

## Checklist

- [x] PR has an informative and human-readable title
- [x] PR is well outlined and documented. See [#12](https://github.com/jarq6c/evaluation_tools/pull/12) for an example
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (see [CONTRIBUTING.md](../CONTRIBUTING.md))
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output) using [numpy docstring](https://numpydoc.readthedocs.io/en/latest/format.html) formatting
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

2022-02-11 14:18 UTC, jarq6c requested changes
Appreciate the updated docs! Seems non-controversial. Just need some clarification on `__init__.py` imports (in terms of best practices/guiding philosophy/Pythonic-ness).

2022-02-11 14:19 UTC, jarq6c commented
Link to #178 ?

2022-02-11 17:51 UTC, aaraney commented on python/nwm_client/src/hydrotools/nwm_client/__init__.py
> +from . import http
Right, it's a matter of opinion and style. Personally, given our audience, I would like to make the experience using hydrotools as intuitive as possible. Here, I am assuming it is more intuitive to a user to import `nwm_client` and then tab complete to see the available submodules. Ex:

```python
from hydrotools import nwm_client

# tab to see exposed subpackage level entities 
nwm_client. # tab tab

nwm_client.html, nwm_client.gcp 
```

To be fair, I am making a fair number of assumptions about _how_ someone might use hydrotools. What do you think about my assumptions? To your point regarding clouding the namespace, im not sure im ready to answer that. I need to think about it more and consider what implications my assumptions might have.

2022-02-25 19:35 UTC, jarq6c approved these changes

2022-02-25 19:35 UTC, jarq6c commented on python/nwm_client/src/hydrotools/nwm_client/__init__.py
> +from . import http
Assuming you've mulled over the implications, let's see how it works out. No need for the PR to go stale because of this minor issue.

2022-03-03 20:43 UTC, merged