Improvements to validation checks
NOAA-OWP/hydrotools pull request #189
Opened 2022-04-18 15:20 UTC by groutr

Some minor improvements to _validation.py that center around the usage of `np.asarray`. Using `np.asarray` over `np.array` can avoid unnecessary copies (ie, when the input is already an array).

When comparing the shapes, we don't need to hold all the arrays in memory.

2022-04-22 14:33 UTC, aaraney commented
@groutr, thanks for the contribution!

I am not sure the `_array_attr` function is necessary. `np.asarray` does [not copy](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html#numpy.asarray) if it receives an input `np.array`. I think it would be more clear to just cast to `np.asarray` and check for the property in places you are proposing to call this method.

2022-04-22 14:33 UTC, aaraney commented
@groutr, thanks for the contribution!

I am not sure the `_array_attr` function is necessary. `np.asarray` does [not copy](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html#numpy.asarray) if it receives an input `np.array`. I think it would be more clear to just cast to `np.asarray` and check for the property in places you are proposing to call this method.

2022-04-22 16:43 UTC, aaraney commented
Ah, I see. That makes a lot of sense. Thanks for clarifying and providing the above example, @groutr.

My only request would be adding some type hints to the function declaration. The return type hint might be difficult to nail down for all cases, so I think the straight path of `npt.ArrayLike` should be fine unless you have a better suggestion.

2022-04-22 21:16 UTC, jarq6c requested changes
Looks good to me. I think we just want to bump the patch version in `python/metrics/src/hydrotools/metrics/_version.py` to `1.2.2`

I tested these changes locally and it is indeed faster. Thanks for the contribution!

2022-04-25 14:43 UTC, aaraney commented
Thanks again, @groutr!

2022-05-03 15:54 UTC, merged